import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Claim clients immediately so the service worker takes control right away
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
// eslint-disable-next-line no-restricted-globals
precacheAndRoute(self.__WB_MANIFEST || []);

// Cleanup old caches
cleanupOutdatedCaches();

// Listen for push events
self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const title = data.title || 'MessageMe';
    const body = data.body || 'You have a new notification';
    const url = (data.data && data.data.url) || '/';

    const options = {
      body,
      icon: '/pwa-192x192.png',
      badge: '/masked-icon.svg',
      vibrate: [100, 50, 100],
      data: {
        url,
        type: data.data?.type,
        conversationId: data.data?.conversationId
      },
      // Require interaction for calls
      requireInteraction: data.data?.type === 'CALL_INCOMING',
      // Tag prevents multiple notifications for the same conversation stacking endlessly
      tag: data.data?.conversationId || data.data?.type || 'default'
    };

    // If it's a message, notify all clients (the tabs) so they can update UI
    // If the tab is visible and focused on the same conversation, we might not want to show a push notification.
    event.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
        let isFocusedAndLookingAtChat = false;

        for (let client of windowClients) {
          // Check if client is focused and looking at the specific chat
          if (client.focused) {
            const urlObj = new URL(client.url);
            if (options.data.conversationId && urlObj.pathname.includes(`/chat/${options.data.conversationId}`)) {
              isFocusedAndLookingAtChat = true;
            }
          }
          // Post message to the client (to update unread badges, etc)
          client.postMessage({
            type: 'PUSH_RECEIVED',
            payload: data
          });
        }

        // Only show notification if the user isn't actively looking at the specific chat
        if (!isFocusedAndLookingAtChat) {
          return self.registration.showNotification(title, options);
        }
      })
    );
  } catch (err) {
    console.error('Error handling push event', err);
    // Fallback if not JSON
    event.waitUntil(
      self.registration.showNotification('MessageMe', {
        body: event.data.text(),
        icon: '/pwa-192x192.png'
      })
    );
  }
});

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const urlToOpen = new URL(event.notification.data.url || '/', self.location.origin).href;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      let matchingClient = null;
      let anyClient = null;

      for (let client of windowClients) {
        anyClient = client;
        if (client.url === urlToOpen) {
          matchingClient = client;
          break;
        }
      }

      // If a window is already open, focus it and navigate if needed
      if (matchingClient) {
        return matchingClient.focus();
      } else if (anyClient) {
        anyClient.focus();
        return anyClient.navigate(urlToOpen);
      } else {
        // If no window is open, open a new one
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
